version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  maven:
    image: maven:3.8.6-openjdk-11
    working_dir: /app
    volumes:
      - .:/app
    command: mvn clean package

  tomcat:
    image: tomcat:9.0
    depends_on:
      - maven
    ports:
      - "8080:8080"
    volumes:
      - ./target/mysqlapp.war:/usr/local/tomcat/webapps/mysqlapp.war

volumes:
  mysql_data: