#version: '3.8' # version of docker-compose
services: # containers to run
  mongodb:  #container name
    image: mongo # docker image name
    container_name: mongodb
    ports:      # port bind host:container
      - "27017:27017"
    environment: # -e variables
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always #ensures the container start when docker start

  mongo-express:  #container name
    image: mongo-express # docker image name
    container_name: mongo-express  
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb   # means start the mongodb container before mongo-express.It does not have to wait to start mongodb first
    restart: always
