#!/usr/bin/env groovy 
pipeline {
    agent any 
    stages {
        stage('Git') {
            steps {
                echo 'Fetch from git' 
            }
        }
        stage('Build') {
            steps {
                echo 'building an apllication' 
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying an application' 
            }
        }
    }
}