#!/usr/bin/env groovy
def gv

pipeline{
    agent any
    tools{
        maven 'maven-3.9'
    }
    stages{
        stage('init'){
            steps{
               gv =  load "java-maven-app/java-maven-app/script.groovy"               
            }
        }
        stage('build jar'){
            steps{
               gv.buildJar()               
            }
        }
        stage('build image'){
            steps{  
                gv.buildImage()
               
            }
        }
        stage('deploy'){
            steps{
                echo "building an application..!"
            }
        }
    }
}